### ISSUE TITLE
Makefile: DIST_NAME whitespace causing errors

### ISSUE THREAD

**Issue by phdsg** [Miserlou/RJModules#12]
`DIST_NAME = RJModules ` << this space after RJModules...

also: what's that `<Paste>` in the last line??

**Comment by Miserlou** [comment]
That looks like vim fuckupery. Fixed, thanks.

**Comment by phdsg** [comment]
looks like teh space is still in there...

**Comment by Miserlou** [comment]
Not sure how that got back in. Pushed again.
