### ISSUE TITLE
Update VERSION in Makefile

### ISSUE THREAD

**Issue by cschol** [Miserlou/RJModules#27]
VERSION in Makefile should be updated to `0.6.0`, removing the `dev` suffix. Thank you!

**Comment by Miserlou** [comment]
Yep!

**Comment by cschol** [comment]
Straggler! #lastoneleft ;)

**Comment by Miserlou** [comment]
Done!

I haven't been paying attention - do I need to do something more? Is there a public buildbox yet?

**Comment by cschol** [comment]
Thanks! No, we are getting the new community repo ready with manifests and submodules and the versions needed to align. Andrew is building the first round of modules, so you should be good.
