### ISSUE TITLE
Randoms

### ISSUE THREAD

**Issue by bitfetcher** [Miserlou/RJModules#37]
Only channel 1 of "Randoms" outputs a signal. Looking at the code, it looks like all three channel blocks in "step" assign to channel 1:

outputs[CH1_OUTPUT].value = distr1(eng);

Maybe a dreaded cut/paste replication error?? :)

Thanks for the great modules!!

**Comment by Miserlou** [comment]
Ah! Right you are! Those first few modules I made are really quite poor!

Thanks for the report, I've just pushed a fix to master!
