### ISSUE TITLE
Rack v1: Invalid tag in plugin.json

### ISSUE THREAD

**Issue by cschol** [Miserlou/RJModules#39]
The manifest validator script found the following issues in the `plugin.json`:

```
Validating RJModules
Acid: invalid tags: Mutiple
```

Please see this link for a list of valid tags: https://github.com/VCVRack/Rack/blob/v1/src/plugin.cpp#L534

**Comment by Miserlou** [comment]
Fixed, thanks. Mutiple -> Multiple.

Is there a `plugin.json` validation checker that I can test with in my makefile?

**Comment by cschol** [comment]
I wrote a script. I might put it somewhere in the near future for people to run themselves.
