### ISSUE TITLE
Displays don't truncate properly

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/RJModules#5]
Some values seem to spill out of the display area.

**Comment by a1laserboy** [comment]
Hi, Just noticed this also on your new build (on OSX 12.12.6), wanted to create a new issue but found you already noticed it.
![screen-shot-2017-12-14-at-18 30 18](https://user-images.githubusercontent.com/13291547/34008472-545a9e5e-e0fd-11e7-8003-b80705809ea3.jpg)

**Comment by Miserlou** [comment]
Yep. It really annoys me. :-D
