### ISSUE TITLE
Win 10 build error

### ISSUE THREAD

**Issue by SteveRussell33** [Miserlou/RJModules#57]
``
g++ -o plugin.dll build/src/Drumpler.cpp.o build/src/PlayableChord.cpp.o build/src/Filter.cpp.o build/src/Filters.cpp.o build/src/Displays.cpp.o build/src/Chord.cpp.o build/src/RJModules.cpp.o build/src/Supersaw.cpp.o build/src/PingPong.cpp.o build/src/Octaves.cpp.o build/src/Buffers.cpp.o build/src/UI.cpp.o build/src/Stutter.cpp.o build/src/Randoms.cpp.o build/src/BigButton.cpp.o build/src/Widener.cpp.o build/src/ReplayKnob.cpp.o build/src/TriggerSwitch.cpp.o build/src/Panner.cpp.o build/src/BPM.cpp.o build/src/Splitter.cpp.o build/src/Core.cpp.o build/src/uQuant.cpp.o build/src/common.cpp.o build/src/TwinLFO.cpp.o build/src/Succulent.cpp.o build/src/Panners.cpp.o build/src/EssEff.cpp.o build/src/Sidechain.cpp.o build/src/RangeLFO.cpp.o build/src/Floats.cpp.o build/src/3xOSC.cpp.o build/src/Integers.cpp.o build/src/vcf.cpp.o build/src/MetaKnob.cpp.o build/src/DryWet.cpp.o build/src/Acid.cpp.o build/src/DSPUtilities.cpp.o build/src/Sequential.cpp.o build/src/DSPMath.cpp.o build/src/RandomFilter.cpp.o build/src/Notes.cpp.o build/src/BitCrush.cpp.o build/src/ChordSeq.cpp.o build/src/PolySidechain.cpp.o build/src/Noise.cpp.o build/src/KTF.cpp.o build/src/Oscillator.cpp.o build/src/Mono.cpp.o build/src/FFTuner.cpp.o build/src/VAStateVariableFilter.cpp.o build/src/Notch.cpp.o build/src/Glides.cpp.o build/src/FilterDelay.cpp.o build/src/MutateSeq.cpp.o build/src/Range.cpp.o build/src/Riser.cpp.o build/src/Buttons.cpp.o build/src/Pluck.cpp.o build/src/BPF.cpp.o build/src/LRMixer.cpp.o build/src/Splitters.cpp.o build/src/Volumes.cpp.o build/src/Bitmap.cpp.o -lsndfile -shared -L../.. -lRack
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsndfile
collect2.exe: error: ld returned 1 exit status
make: *** [../../compile.mk:59: plugin.dll] Error 1
``

**Comment by cschol** [comment]
Same for Mac platform (when cross-compiling):

```
x86_64-apple-darwin17-clang++ -o plugin.dylib build/src/Volumes.cpp.o build/src/Splitters.cpp.o build/src/LRMixer.cpp.o build/src/BPF.cpp.o build/src/MutateSeq.cpp.o build/src/DryWet.cpp.o build/src/Brickwall.cpp.o build/src/ChordSeq.cpp.o build/src/Riser.cpp.o build/src/Range.cpp.o build/src/ReplayKnob.cpp.
o build/src/Octaves.cpp.o build/src/Splitter.cpp.o build/src/VAStateVariableFilter.cpp.o build/src/Oscillator.cpp.o build/src/Mono.cpp.o build/src/KTF.cpp.o build/src/Chord.cpp.o build/src/UI.cpp.o build/src/Glides.cpp.o build/src/Panner.cpp.o build/src/Pluck.cpp.o build/src/PolySidechain.cpp.o build/src/Fil
terDelay.cpp.o build/src/BitCrush.cpp.o build/src/Notes.cpp.o build/src/DSPMath.cpp.o build/src/Sequential.cpp.o build/src/DSPUtilities.cpp.o build/src/Filter.cpp.o build/src/Buttons.cpp.o build/src/RandomFilter.cpp.o build/src/Panners.cpp.o build/src/MetaKnob.cpp.o build/src/Noise.cpp.o build/src/Integers.c
pp.o build/src/Notch.cpp.o build/src/Floats.cpp.o build/src/Displays.cpp.o build/src/RangeLFO.cpp.o build/src/Sidechain.cpp.o build/src/TriggerSwitch.cpp.o build/src/Succulent.cpp.o build/src/TwinLFO.cpp.o build/src/common.cpp.o build/src/3xOSC.cpp.o build/src/Core.cpp.o build/src/RJModules.cpp.o build/src/B
PM.cpp.o build/src/EssEff.cpp.o build/src/vcf.cpp.o build/src/Widener.cpp.o build/src/BigButton.cpp.o build/src/Randoms.cpp.o build/src/PingPong.cpp.o build/src/Buffers.cpp.o build/src/uQuant.cpp.o build/src/Supersaw.cpp.o build/src/Acid.cpp.o build/src/FFTuner.cpp.o build/src/Filters.cpp.o build/src/Stutter
.cpp.o build/src/PlayableChord.cpp.o build/src/Drumpler.cpp.o build/src/Bitmap.cpp.o -lsndfile -shared -undefined dynamic_lookup -stdlib=libc++ -mmacosx-version-min=10.7                                                                                                                                           
ld: library not found for -lsndfile                                                                                                                                                                                                                                                                                 
clang: error: linker command failed with exit code 1 (use -v to see invocation)                                                                                                                                                                                                                                     
/home/cschol/src/Rack-SDK/Rack-SDK/compile.mk:59: recipe for target 'plugin.dylib' failed
```

**Comment by Miserlou** [comment]
Should be better now.

**Comment by cschol** [comment]
Still tries to link against `libsndfile` and fails for both platforms.

`Makefile` still adds `libsndfile` to `LDFLAGS`.

**Comment by SteveRussell33** [comment]
Success as of https://github.com/Miserlou/RJModules/commit/f92f511909ccf2d6c29903ef4e98d7d62f07b546
