### ISSUE TITLE
OCTO lfo

### ISSUE THREAD

**Issue by vcvrackideas** [Miserlou/RJModules#63]
Hi! Octo is pretty nice module! But it seems to me it behaves strange now - cv input doesn't work and lights don't show correct visual info on what's going on with each output, kinda strange behavior they all have. I hope it's just under development and really looking forward for proper version. Thank you for your work and Happy new year!

**Comment by Miserlou** [comment]
Hey thanks, but Octo is still a WIP! Anything on Github that doesnt bump
the package version should be considered unstable! :) Will fix the lights,
attenuation and oscillator timings once this hangover blows over - I always
do the layout and interface before the innards!

**Comment by Miserlou** [comment]
Okay, Octo is "done"! Feedback is welcome! Enjoy!
