### ISSUE TITLE
Left Hand Right Hand triggers both outputs

### ISSUE THREAD

**Issue by jimallman** [Miserlou/RJModules#65]
I've been looking for a keyboard splitter for some time, so I was glad to see this. The UI is nice and simple, but in my experience it often triggers both outputs when reading an incoming V/Oct signal (usually the right one, then the wrong one after a brief delay).

Does this module support polyphony? If not, that might be my problem..

**Comment by Miserlou** [comment]
Heiya, LHRH was kind of a quick hack I threw together as an experiment, so I'm sure there are some bugs like this in it! You might have to change the polyphony mode in the right click menu first. If this is the case, I'll try to change the default. If that doesn't help, please send me an easy way to reproduce the bug so I can try to patch it. Thanks!

**Comment by jimallman** [comment]
I just tried updating all plugins, and now it's working correctly for me, polyphony included. Odd, because I don't see any obvious fixes here. Anyway, it's a very handy module. Thanks again!
