### ISSUE TITLE
Instant crash with Instro

### ISSUE THREAD

**Issue by disconcert** [Miserlou/RJModules#72]
VCV crashes every time I load Instro into the rack

Log:
[227.674 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
36: ZN4rack10appDestroyEv 0x456435
35: raise 0x62b8ac60
34: abort 0x62b8f270
33: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x6fc5f170
32: ZN10__cxxabiv111__terminateEPFvvE 0x6fc581b0
31: ZSt9terminatev 0x6fd302b0
30: _cxa_throw 0x6fd39080
29: ZNK3stk3Stk11handleErrorENS_8StkError4TypeE 0xb67d702
28: ZN3stk8FileRead4openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0xb6d9f4a
27: ZN3stk8FileLoopC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbbmmb 0xb663fa4
26: ZN3stk6RhodeyC1Ev 0xb66ec56
25: ZN6InstroC1Ev 0xb73e8e0
24: ZZN4rack11createModelI6Instro12InstroWidgetEEPNS_6plugin5ModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel18createModuleWidgetEv 0xb778fc0
23: ZN4rack3app11AudioWidget12setAudioPortEPNS_5audio4PortE 0x49839c
22: ZN4rack3app8ModelBox8onButtonERKNS_5event6ButtonE 0x75cbc0
21: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
20: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
19: ZN4rack6widget6Widget8onButtonERKNS_5event6ButtonE 0x7726f0
18: ZN4rack2ui12ScrollWidget8onButtonERKNS_5event6ButtonE 0x4a3ed4
17: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
16: ZN4rack3app14BrowserOverlay8onButtonERKNS_5event6ButtonE 0x7530d0
15: ZN4rack6widget12OpaqueWidget8onButtonERKNS_5event6ButtonE 0x771cd0
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
13: ZN4rack7updater17isUpdateAvailableEv 0x45914e
12: glfwPlatformUnlockMutex 0x4d78ae
11: CallWindowProcW 0x61da57b0
10: CallWindowProcW 0x61da57b0
9: glPushClientAttrib 0x350b3770
8: CallWindowProcW 0x61da57b0
7: DispatchMessageW 0x61da5370
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x63927bc0
0: RtlUserThreadStart 0x63aaceb0

**Comment by Miserlou** [comment]
This is already fixed in master, but not in the published version. Thanks for trying it out!
