### ISSUE TITLE
Loading a patch with Gluten crashes Rack [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [Miserlou/RJModules#73]
[12.004 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
33: ZN4rack10appDestroyEv 0x456d75
32: raise 0xe1a6ac70
31: abort 0xe1a6f270
30: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x6fc5f170
29: ZN10__cxxabiv111__terminateEPFvvE 0x6fc581b0
28: ZSt9terminatev 0x6fd302b0
27: _cxa_throw 0x6fd39080
26: ZN3stk3Stk11handleErrorENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8StkError4TypeE 0x133db6f8
25: ZNK3stk3Stk11handleErrorENS_8StkError4TypeE 0x133dbb04
24: ZN3stk8FileRead4openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0x13384542
23: ZN3stk8FileReadC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0x133848a0
22: ZN3stk9Granulate8openFileENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb 0x1339432e
21: ZN16GlutenFreeWidget8fromJsonEP6json_t 0x1340b030
20: ZN4rack3app10RackWidget11onDragHoverERKNS_5event9DragHoverE 0x48d520
19: ZN4rack3app10RackWidget8fromJsonEP6json_t 0x48de6e
18: ZN4rack12PatchManager8fromJsonEP6json_t 0x48746a
17: ZN4rack12PatchManager4loadENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x487812
16: ZN4rack12PatchManager10loadDialogEv 0x4879aa
15: ZN4rack3app5Scene10onHoverKeyERKNS_5event8HoverKeyE 0x492588
14: ZN4rack5event5State9handleKeyENS_4math3VecEiiii 0x458f46
13: ZN4rack7updater17isUpdateAvailableEv 0x459a8e
12: glfwPlatformUnlockMutex 0x4d7e2e
11: DispatchMessageW 0xe4336da0
10: CallWindowProcW 0xe4336ca0
9: glPushClientAttrib 0xc4511490
8: DispatchMessageW 0xe4336da0
7: DispatchMessageW 0xe4336da0
6: glfwPlatformPollEvents 0x4db4e6
5: ZN4rack6Window3runEv 0x459e86
4: main 0x7838a0
3: main 0x7838a0
2: main 0x7838a0
1: BaseThreadInitThunk 0xe4577960
0: RtlUserThreadStart 0xe477a250

**Comment by Miserlou** [comment]
God dammit. Does EssEff work for you?

**Comment by Miserlou** [comment]
Ah, this is only re-loading a patch?

**Comment by SteveRussell33** [comment]
EssEff is fine here.

Loading a patch with Gluten or re-opening rack with an auto-saved patch.

**Comment by Miserlou** [comment]
Okay, thank you for reporting. I'm bad at windows compatibility..

**Comment by cschol** [comment]
Same issue on Linux platform. Gluten crashes when loading a `.wav` file (24 bit, 48kHz, if that matters).

Also, when loading **any other** kind of file (e.g. a source file, for testing) it also crashes Rack. It should never crash.

**Comment by Miserlou** [comment]
Should be sorted now (by limiting OS that can load until it's fully sussed), also restricts file loads to supported WAV and AIFF formats.

**Comment by SteveRussell33** [comment]
Crashes loading a WAV file:

[38.707 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
27: ZN4rack10appDestroyEv 0x456d75
26: raise 0x1d16ac70
25: abort 0x1d16f270
24: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x6fc5f170
23: ZN10__cxxabiv111__terminateEPFvvE 0x6fc581b0
22: ZSt9terminatev 0x6fd302b0
21: _cxa_throw 0x6fd39080
20: ZN3stk3Stk11handleErrorENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8StkError4TypeE 0x1344b6f8
19: ZNK3stk3Stk11handleErrorENS_8StkError4TypeE 0x1344bb04
18: ZN3stk8FileRead4openENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0x133f4542
17: ZN3stk8FileReadC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbjmd 0x133f48a0
16: ZN3stk9Granulate8openFileENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb 0x1340432e
15: ZN13LoadWavButton11onDragStartERKN4rack5event9DragStartE 0x1346ed10
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x458008
13: ZN4rack7updater17isUpdateAvailableEv 0x459a8e
12: glfwPlatformUnlockMutex 0x4d7e2e
11: DispatchMessageW 0x1d476da0
10: CallWindowProcW 0x1d476ca0
9: glPushClientAttrib 0x751490
8: DispatchMessageW 0x1d476da0
7: DispatchMessageW 0x1d476da0
6: glfwPlatformPollEvents 0x4db4e6
5: ZN4rack6Window3runEv 0x459e86
4: main 0x7838a0
3: main 0x7838a0
2: main 0x7838a0
1: BaseThreadInitThunk 0x1d037960
0: RtlUserThreadStart 0x1f72a240

**Comment by cschol** [comment]
Same here on Linux:

```
#0  0x00007ff3fd011e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff3fd013801 in __GI_abort () at abort.c:79
#2  0x000055f8224e5581 in fatalSignalHandler(int) (sig=<optimized out>) at src/main.cpp:52
#3  0x00007ff3fd011f20 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ff3fd011e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#5  0x00007ff3fd013801 in __GI_abort () at abort.c:79
#6  0x00007ff3fda06957 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ff3fda0cab6 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ff3fda0caf1 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ff3fda0cd24 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ff3ec343202 in stk::Stk::handleError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, stk::StkError::Type) (message="FileRead: /home/cschol/production/monoscene/snapshots/2019-11-03-Truth_20191103_151819_pAgk82_MR2_XmGNwtjw.wav contains an unsupported data format type (256).", type=type@entry=stk::StkError::FILE_ERROR) at src/Stk.cpp:223
#11 0x00007ff3ec3432f1 in stk::Stk::handleError(stk::StkError::Type) const (this=this@entry=0x7ffe5e0a19b0, type=type@entry=stk::StkError::FILE_ERROR) at src/Stk.cpp:197
#12 0x00007ff3ec345e8c in stk::FileRead::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, unsigned int, unsigned long, double) (this=this@entry=0x7ffe5e0a19b0, fileName="/home/cschol/production/monoscene/snapshots/2019-11-03-Truth_20191103_151819_pAgk82_MR2_XmGNwtjw.wav", typeRaw=typeRaw@entry=false, nChannels=nChannels@entry=1, format=format@entry=2, rate=rate@entry=22050) at src/FileRead.cpp:121
#13 0x00007ff3ec346013 in stk::FileRead::FileRead(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, unsigned int, unsigned long, double) (this=0x7ffe5e0a19b0, fileName=..., typeRaw=<optimized out>, nChannels=1, format=2, rate=22050) at src/FileRead.cpp:52
#14 0x00007ff3ec2f1190 in stk::Granulate::openFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (this=this@entry=0x55f82523af80, fileName="/home/cschol/production/monoscene/snapshots/2019-11-03-Truth_20191103_151819_pAgk82_MR2_XmGNwtjw.wav", typeRaw=typeRaw@entry=false) at src/Granulate.cpp:89
#15 0x00007ff3ec384391 in GlutenFree::loadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (path=" \262v%\370U\000\000d\000\000\000\000\000\000\000d\000\000\000\000\000\000\000\000<\373m)+ƅ\000\000\000\000\000\000\000\000\300O\021$\370U\000\000\020\033\n^\376\177\000\000\240\033\n^\376\177\000\000\360\337n%\370U\000\000d\000\000\000\000\000\000\000d\000\000\000\000\000\000\000\000\300)D\000\000\251C\000\000\000\000\001\000\000\000\000<\373m)+ƅ\000\000\000\000\000\000\000\000\360\017\006%\370U\000\000\200\034\n^\376\177\000\000\060σ#\370U\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000 =\314#\370U\000\000g.N\"\370U\000\000\220܀#\370U\000\000\270\033\n^\376\177\000\001\000\001\n^\376\177\000\000"..., this=0x55f82523ae50) at src/GlutenFree.cpp:163
#16 0x00007ff3ec384391 in LoadWavButton::onDragStart(rack::event::DragStart const&) (this=0x55f825060ff0, e=...) at src/GlutenFree.cpp:230
#17 0x000055f8224e2e67 in rack::event::State::setDragged(rack::widget::Widget*, int) (button=0, w=<optimized out>, this=0x55f82383cf30) at src/event.cpp:54
#18 0x000055f8224e2e67 in rack::event::State::handleButton(rack::math::Vec, int, int, int) (this=0x55f82383cf30, pos=..., button=0, action=1, mods=<optimized out>) at src/event.cpp:133
#19 0x000055f82257c449 in processEvent (event=0x7ffe5e0a1c80) at /home/cschol/src/Rack-1.0/dep/glfw/src/x11_window.c:1398
#20 0x000055f82257c449 in _glfwPlatformPollEvents () at /home/cschol/src/Rack-1.0/dep/glfw/src/x11_window.c:2696
#21 0x000055f822573a50 in glfwPollEvents () at /home/cschol/src/Rack-1.0/dep/glfw/src/window.c:1072
#22 0x000055f8224dc2f0 in rack::Window::run() (this=0x55f823cfcb60) at src/window.cpp:343
#23 0x000055f8224558dc in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:203
```
